// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdQSTgx-5FbNzZPNo5YcZyqvb51-JzdC4',
    appId: '1:774096063296:web:f1459417880f1e6770c8a5',
    messagingSenderId: '774096063296',
    projectId: 'tpdeappmobile',
    authDomain: 'tpdeappmobile.firebaseapp.com',
    storageBucket: 'tpdeappmobile.appspot.com',
    measurementId: 'G-1C77GKXCKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIUgwA4QYypkk7VapdH9dt-DbIBXL-Xns',
    appId: '1:774096063296:android:d21c27d6a4f72b5070c8a5',
    messagingSenderId: '774096063296',
    projectId: 'tpdeappmobile',
    storageBucket: 'tpdeappmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Nqi8Qa-qP_YpuNKUEVqJjZnmK0ZzWcE',
    appId: '1:774096063296:ios:9b10e4eaf83d588b70c8a5',
    messagingSenderId: '774096063296',
    projectId: 'tpdeappmobile',
    storageBucket: 'tpdeappmobile.appspot.com',
    iosBundleId: 'com.example.tpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Nqi8Qa-qP_YpuNKUEVqJjZnmK0ZzWcE',
    appId: '1:774096063296:ios:9b10e4eaf83d588b70c8a5',
    messagingSenderId: '774096063296',
    projectId: 'tpdeappmobile',
    storageBucket: 'tpdeappmobile.appspot.com',
    iosBundleId: 'com.example.tpp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdQSTgx-5FbNzZPNo5YcZyqvb51-JzdC4',
    appId: '1:774096063296:web:f6289f692b043f1870c8a5',
    messagingSenderId: '774096063296',
    projectId: 'tpdeappmobile',
    authDomain: 'tpdeappmobile.firebaseapp.com',
    storageBucket: 'tpdeappmobile.appspot.com',
    measurementId: 'G-2QMJLZKH4K',
  );
}
